name: Deploy won-q test server for Frontend developers

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set secret.yml file
        run: |
          echo "$SECRET_YML_CONTENT" > ./src/main/resources/secret.yml
        env:
          SECRET_YML_CONTENT: ${{ secrets.SECRET_YML_DEV }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Spring Boot Application
        run: ./gradlew bootJar

      - name: Stop existing application
        run: |
          pkill -f 'java -jar' || true

      - name: Run Spring Boot Application
        run: |
          nohup java -jar ./build/libs/*.jar > app.log 2>&1 &
